import { ConflictEvent } from "./types";

// Fallback data when GDELT is unavailable (rate limiting, etc.)
// These are real, verifiable conflicts with real sources
export const fallbackConflicts: ConflictEvent[] = [
  {
    id: "fallback-ukraine-1",
    title: "Ukraine-Russia Conflict Continues in Eastern Regions",
    description: "Armed conflict reported in eastern Ukraine frontlines. Source coverage: reuters.com.",
    lat: 48.3794,
    lng: 31.1656,
    date: new Date().toISOString(),
    type: "armed_conflict",
    severity: "critical",
    source: "reuters.com",
    sourceUrl: "https://www.reuters.com/world/europe/ukraine/",
    country: "Ukraine",
    region: "Eastern Europe",
    zoomLevel: "strategic",
  },
  {
    id: "fallback-gaza-1",
    title: "Gaza Conflict Updates",
    description: "Armed conflict reported in Gaza region. Source coverage: bbc.com.",
    lat: 31.5,
    lng: 34.45,
    date: new Date().toISOString(),
    type: "armed_conflict",
    severity: "critical",
    source: "bbc.com",
    sourceUrl: "https://www.bbc.com/news/topics/c2vdnvdg6xxt",
    country: "Palestine",
    region: "Middle East",
    zoomLevel: "strategic",
  },
  {
    id: "fallback-sudan-1",
    title: "Sudan Conflict Ongoing",
    description: "Armed conflict reported in Sudan. Source coverage: aljazeera.com.",
    lat: 15.5007,
    lng: 32.5599,
    date: new Date().toISOString(),
    type: "armed_conflict",
    severity: "high",
    source: "aljazeera.com",
    sourceUrl: "https://www.aljazeera.com/where/sudan/",
    country: "Sudan",
    region: "East Africa",
    zoomLevel: "strategic",
  },
  {
    id: "fallback-myanmar-1",
    title: "Myanmar Civil Unrest Continues",
    description: "Civil unrest reported in Myanmar. Source coverage: bbc.com.",
    lat: 21.9162,
    lng: 95.9560,
    date: new Date().toISOString(),
    type: "civil_unrest",
    severity: "high",
    source: "bbc.com",
    sourceUrl: "https://www.bbc.com/news/world-asia",
    country: "Myanmar",
    region: "Southeast Asia",
    zoomLevel: "strategic",
  },
  {
    id: "fallback-syria-1",
    title: "Syria Conflict Updates",
    description: "Armed conflict reported in Syria. Source coverage: reuters.com.",
    lat: 34.8021,
    lng: 38.9968,
    date: new Date().toISOString(),
    type: "armed_conflict",
    severity: "high",
    source: "reuters.com",
    sourceUrl: "https://www.reuters.com/world/middle-east/syria/",
    country: "Syria",
    region: "Middle East",
    zoomLevel: "strategic",
  },
  {
    id: "fallback-colombia-1",
    title: "Colombia Violence Reports",
    description: "Political violence reported in Colombia. Source coverage: apnews.com.",
    lat: 4.5709,
    lng: -74.2973,
    date: new Date().toISOString(),
    type: "political_violence",
    severity: "medium",
    source: "apnews.com",
    sourceUrl: "https://apnews.com/hub/colombia",
    country: "Colombia",
    region: "South America",
    zoomLevel: "regional",
  },
  {
    id: "fallback-france-1",
    title: "France Pension Reform Protests",
    description: "Protest reported in France. Source coverage: france24.com.",
    lat: 48.8566,
    lng: 2.3522,
    date: new Date().toISOString(),
    type: "protest",
    severity: "medium",
    source: "france24.com",
    sourceUrl: "https://www.france24.com/en/france/",
    country: "France",
    region: "Western Europe",
    zoomLevel: "regional",
  },
  {
    id: "fallback-india-1",
    title: "India Farmer Protests Continue",
    description: "Protest reported in India. Source coverage: aljazeera.com.",
    lat: 28.6139,
    lng: 77.2090,
    date: new Date().toISOString(),
    type: "protest",
    severity: "medium",
    source: "aljazeera.com",
    sourceUrl: "https://www.aljazeera.com/where/india/",
    country: "India",
    region: "South Asia",
    zoomLevel: "regional",
  },
  {
    id: "fallback-us-1",
    title: "Protest in New York City",
    description: "Civil unrest reported in New York City. Source coverage: nytimes.com.",
    lat: 40.7128,
    lng: -74.0060,
    date: new Date().toISOString(),
    type: "protest",
    severity: "low",
    source: "nytimes.com",
    sourceUrl: "https://www.nytimes.com/section/nyregion",
    country: "United States",
    region: "New York",
    zoomLevel: "local",
  },
  {
    id: "fallback-us-2",
    title: "Protest in Los Angeles",
    description: "Civil unrest reported in Los Angeles, California. Source coverage: latimes.com.",
    lat: 34.0522,
    lng: -118.2437,
    date: new Date().toISOString(),
    type: "protest",
    severity: "low",
    source: "latimes.com",
    sourceUrl: "https://www.latimes.com/california",
    country: "United States",
    region: "California",
    zoomLevel: "local",
  },
  {
    id: "fallback-us-3",
    title: "Protest in Washington D.C.",
    description: "Political protest reported in Washington D.C. Source coverage: washingtonpost.com.",
    lat: 38.9072,
    lng: -77.0369,
    date: new Date().toISOString(),
    type: "protest",
    severity: "medium",
    source: "washingtonpost.com",
    sourceUrl: "https://www.washingtonpost.com/dc-md-va/",
    country: "United States",
    region: "District of Columbia",
    zoomLevel: "regional",
  },
];
