import { ConflictEvent } from "./types";

// Fallback data when GDELT is unavailable (rate limiting, etc.)
// These are real, verifiable conflicts with real sources
export const fallbackConflicts: ConflictEvent[] = [
  {
    id: "fallback-ukraine-1",
    title: "Ukraine-Russia Conflict Continues in Eastern Regions",
    description: "Armed conflict reported in eastern Ukraine frontlines. Source coverage: reuters.com.",
    lat: 48.3794,
    lng: 31.1656,
    date: new Date().toISOString(),
    type: "armed_conflict",
    severity: "critical",
    source: "reuters.com",
    sourceUrl: "https://www.reuters.com/world/europe/ukraine/",
    country: "Ukraine",
    region: "Eastern Europe",
    zoomLevel: "strategic",
  },
  {
    id: "fallback-gaza-1",
    title: "Gaza Conflict Updates",
    description: "Armed conflict reported in Gaza region. Source coverage: bbc.com.",
    lat: 31.5,
    lng: 34.45,
    date: new Date().toISOString(),
    type: "armed_conflict",
    severity: "critical",
    source: "bbc.com",
    sourceUrl: "https://www.bbc.com/news/topics/c2vdnvdg6xxt",
    country: "Palestine",
    region: "Middle East",
    zoomLevel: "strategic",
  },
  {
    id: "fallback-sudan-1",
    title: "Sudan Conflict Ongoing",
    description: "Armed conflict reported in Sudan. Source coverage: aljazeera.com.",
    lat: 15.5007,
    lng: 32.5599,
    date: new Date().toISOString(),
    type: "armed_conflict",
    severity: "high",
    source: "aljazeera.com",
    sourceUrl: "https://www.aljazeera.com/where/sudan/",
    country: "Sudan",
    region: "East Africa",
    zoomLevel: "strategic",
  },
  {
    id: "fallback-myanmar-1",
    title: "Myanmar Civil Unrest Continues",
    description: "Civil unrest reported in Myanmar. Source coverage: bbc.com.",
    lat: 21.9162,
    lng: 95.9560,
    date: new Date().toISOString(),
    type: "civil_unrest",
    severity: "high",
    source: "bbc.com",
    sourceUrl: "https://www.bbc.com/news/world-asia",
    country: "Myanmar",
    region: "Southeast Asia",
    zoomLevel: "strategic",
  },
  {
    id: "fallback-syria-1",
    title: "Syria Conflict Updates",
    description: "Armed conflict reported in Syria. Source coverage: reuters.com.",
    lat: 34.8021,
    lng: 38.9968,
    date: new Date().toISOString(),
    type: "armed_conflict",
    severity: "high",
    source: "reuters.com",
    sourceUrl: "https://www.reuters.com/world/middle-east/syria/",
    country: "Syria",
    region: "Middle East",
    zoomLevel: "strategic",
  },
  {
    id: "fallback-colombia-1",
    title: "Colombia Violence Reports",
    description: "Political violence reported in Colombia. Source coverage: apnews.com.",
    lat: 4.5709,
    lng: -74.2973,
    date: new Date().toISOString(),
    type: "political_violence",
    severity: "medium",
    source: "apnews.com",
    sourceUrl: "https://apnews.com/hub/colombia",
    country: "Colombia",
    region: "South America",
    zoomLevel: "regional",
  },
  {
    id: "fallback-france-1",
    title: "France Pension Reform Protests",
    description: "Protest reported in France. Source coverage: france24.com.",
    lat: 48.8566,
    lng: 2.3522,
    date: new Date().toISOString(),
    type: "protest",
    severity: "medium",
    source: "france24.com",
    sourceUrl: "https://www.france24.com/en/france/",
    country: "France",
    region: "Western Europe",
    zoomLevel: "regional",
  },
  {
    id: "fallback-india-1",
    title: "India Farmer Protests Continue",
    description: "Protest reported in India. Source coverage: aljazeera.com.",
    lat: 28.6139,
    lng: 77.2090,
    date: new Date().toISOString(),
    type: "protest",
    severity: "medium",
    source: "aljazeera.com",
    sourceUrl: "https://www.aljazeera.com/where/india/",
    country: "India",
    region: "South Asia",
    zoomLevel: "regional",
  },
];
