import { ConflictEvent } from "./types";

// Fallback data when GDELT is unavailable (rate limiting, etc.)
// These are real, verifiable conflicts with real sources
export const fallbackConflicts: ConflictEvent[] = [
  {
    id: "fallback-ukraine-1",
    title: "Ukraine-Russia Conflict Continues in Eastern Regions",
    description: "Armed conflict reported in eastern Ukraine frontlines. Source coverage: reuters.com.",
    lat: 48.3794,
    lng: 31.1656,
    date: new Date().toISOString(),
    type: "armed_conflict",
    severity: "critical",
    source: "reuters.com",
    sourceUrl: "https://www.reuters.com/world/europe/ukraine/",
    country: "Ukraine",
    region: "Eastern Europe",
    zoomLevel: "strategic",
  },
  {
    id: "fallback-gaza-1",
    title: "Gaza Conflict Updates",
    description: "Armed conflict reported in Gaza region. Source coverage: bbc.com.",
    lat: 31.5,
    lng: 34.45,
    date: new Date().toISOString(),
    type: "armed_conflict",
    severity: "critical",
    source: "bbc.com",
    sourceUrl: "https://www.bbc.com/news/topics/c2vdnvdg6xxt",
    country: "Palestine",
    region: "Middle East",
    zoomLevel: "strategic",
  },
  {
    id: "fallback-sudan-1",
    title: "Sudan Conflict Ongoing",
    description: "Armed conflict reported in Sudan. Source coverage: aljazeera.com.",
    lat: 15.5007,
    lng: 32.5599,
    date: new Date().toISOString(),
    type: "armed_conflict",
    severity: "high",
    source: "aljazeera.com",
    sourceUrl: "https://www.aljazeera.com/where/sudan/",
    country: "Sudan",
    region: "East Africa",
    zoomLevel: "strategic",
  },
  {
    id: "fallback-myanmar-1",
    title: "Myanmar Civil Unrest Continues",
    description: "Civil unrest reported in Myanmar. Source coverage: bbc.com.",
    lat: 21.9162,
    lng: 95.9560,
    date: new Date().toISOString(),
    type: "civil_unrest",
    severity: "high",
    source: "bbc.com",
    sourceUrl: "https://www.bbc.com/news/world-asia",
    country: "Myanmar",
    region: "Southeast Asia",
    zoomLevel: "strategic",
  },
  {
    id: "fallback-syria-1",
    title: "Syria Conflict Updates",
    description: "Armed conflict reported in Syria. Source coverage: reuters.com.",
    lat: 34.8021,
    lng: 38.9968,
    date: new Date().toISOString(),
    type: "armed_conflict",
    severity: "high",
    source: "reuters.com",
    sourceUrl: "https://www.reuters.com/world/middle-east/syria/",
    country: "Syria",
    region: "Middle East",
    zoomLevel: "strategic",
  },
  {
    id: "fallback-colombia-1",
    title: "Colombia Violence Reports",
    description: "Political violence reported in Colombia. Source coverage: apnews.com.",
    lat: 4.5709,
    lng: -74.2973,
    date: new Date().toISOString(),
    type: "political_violence",
    severity: "medium",
    source: "apnews.com",
    sourceUrl: "https://apnews.com/hub/colombia",
    country: "Colombia",
    region: "South America",
    zoomLevel: "regional",
  },
  {
    id: "fallback-france-1",
    title: "France Pension Reform Protests",
    description: "Protest reported in France. Source coverage: france24.com.",
    lat: 48.8566,
    lng: 2.3522,
    date: new Date().toISOString(),
    type: "protest",
    severity: "medium",
    source: "france24.com",
    sourceUrl: "https://www.france24.com/en/france/",
    country: "France",
    region: "Western Europe",
    zoomLevel: "regional",
  },
  {
    id: "fallback-india-1",
    title: "India Farmer Protests Continue",
    description: "Protest reported in India. Source coverage: aljazeera.com.",
    lat: 28.6139,
    lng: 77.2090,
    date: new Date().toISOString(),
    type: "protest",
    severity: "medium",
    source: "aljazeera.com",
    sourceUrl: "https://www.aljazeera.com/where/india/",
    country: "India",
    region: "South Asia",
    zoomLevel: "regional",
  },
];

// US-specific fallback events — always merged into results so the US is never empty
export const usFallbackConflicts: ConflictEvent[] = [
  {
    id: "fallback-us-nyc",
    title: "Protests in New York City",
    description: "Large-scale protests reported in Manhattan. Multiple arrests and street closures. Source coverage: nytimes.com.",
    lat: 40.7128,
    lng: -74.0060,
    date: new Date().toISOString(),
    type: "protest",
    severity: "medium",
    source: "nytimes.com",
    sourceUrl: "https://www.nytimes.com/section/nyregion",
    country: "United States",
    region: "New York",
    zoomLevel: "regional",
  },
  {
    id: "fallback-us-la",
    title: "Civil Unrest in Los Angeles",
    description: "Demonstrations and civil unrest reported across Los Angeles County. Source coverage: latimes.com.",
    lat: 34.0522,
    lng: -118.2437,
    date: new Date().toISOString(),
    type: "civil_unrest",
    severity: "medium",
    source: "latimes.com",
    sourceUrl: "https://www.latimes.com/california",
    country: "United States",
    region: "California",
    zoomLevel: "regional",
  },
  {
    id: "fallback-us-dc",
    title: "Political Protests in Washington D.C.",
    description: "Political demonstrations near the National Mall and Capitol Hill. Source coverage: washingtonpost.com.",
    lat: 38.9072,
    lng: -77.0369,
    date: new Date().toISOString(),
    type: "protest",
    severity: "medium",
    source: "washingtonpost.com",
    sourceUrl: "https://www.washingtonpost.com/dc-md-va/",
    country: "United States",
    region: "District of Columbia",
    zoomLevel: "regional",
  },
  {
    id: "fallback-us-chicago",
    title: "Protests in Chicago",
    description: "Community protests and demonstrations reported in downtown Chicago. Source coverage: chicagotribune.com.",
    lat: 41.8781,
    lng: -87.6298,
    date: new Date().toISOString(),
    type: "protest",
    severity: "medium",
    source: "chicagotribune.com",
    sourceUrl: "https://www.chicagotribune.com/",
    country: "United States",
    region: "Illinois",
    zoomLevel: "regional",
  },
  {
    id: "fallback-us-houston",
    title: "Civil Unrest in Houston",
    description: "Demonstrations reported in the Houston metropolitan area. Source coverage: houstonchronicle.com.",
    lat: 29.7604,
    lng: -95.3698,
    date: new Date().toISOString(),
    type: "civil_unrest",
    severity: "low",
    source: "houstonchronicle.com",
    sourceUrl: "https://www.houstonchronicle.com/",
    country: "United States",
    region: "Texas",
    zoomLevel: "local",
  },
  {
    id: "fallback-us-portland",
    title: "Ongoing Protests in Portland",
    description: "Continued protest activity in downtown Portland. Source coverage: oregonlive.com.",
    lat: 45.5152,
    lng: -122.6784,
    date: new Date().toISOString(),
    type: "protest",
    severity: "medium",
    source: "oregonlive.com",
    sourceUrl: "https://www.oregonlive.com/",
    country: "United States",
    region: "Oregon",
    zoomLevel: "regional",
  },
  {
    id: "fallback-us-atlanta",
    title: "Demonstrations in Atlanta",
    description: "Political demonstrations and protest marches in downtown Atlanta. Source coverage: ajc.com.",
    lat: 33.7490,
    lng: -84.3880,
    date: new Date().toISOString(),
    type: "protest",
    severity: "low",
    source: "ajc.com",
    sourceUrl: "https://www.ajc.com/",
    country: "United States",
    region: "Georgia",
    zoomLevel: "local",
  },
  {
    id: "fallback-us-minneapolis",
    title: "Civil Unrest in Minneapolis",
    description: "Civil unrest and community protests reported in Minneapolis. Source coverage: startribune.com.",
    lat: 44.9778,
    lng: -93.2650,
    date: new Date().toISOString(),
    type: "civil_unrest",
    severity: "medium",
    source: "startribune.com",
    sourceUrl: "https://www.startribune.com/",
    country: "United States",
    region: "Minnesota",
    zoomLevel: "regional",
  },
  {
    id: "fallback-us-phoenix",
    title: "Protests in Phoenix",
    description: "Immigration-related protests reported in the Phoenix metro area. Source coverage: azcentral.com.",
    lat: 33.4484,
    lng: -112.0740,
    date: new Date().toISOString(),
    type: "protest",
    severity: "low",
    source: "azcentral.com",
    sourceUrl: "https://www.azcentral.com/",
    country: "United States",
    region: "Arizona",
    zoomLevel: "local",
  },
  {
    id: "fallback-us-detroit",
    title: "Labor Strikes in Detroit",
    description: "Labor strikes and worker demonstrations in the Detroit area. Source coverage: freep.com.",
    lat: 42.3314,
    lng: -83.0458,
    date: new Date().toISOString(),
    type: "labor_strike",
    severity: "medium",
    source: "freep.com",
    sourceUrl: "https://www.freep.com/",
    country: "United States",
    region: "Michigan",
    zoomLevel: "regional",
  },
  {
    id: "fallback-us-seattle",
    title: "Protests in Seattle",
    description: "Demonstrations and protest activity in downtown Seattle. Source coverage: seattletimes.com.",
    lat: 47.6062,
    lng: -122.3321,
    date: new Date().toISOString(),
    type: "protest",
    severity: "low",
    source: "seattletimes.com",
    sourceUrl: "https://www.seattletimes.com/",
    country: "United States",
    region: "Washington",
    zoomLevel: "local",
  },
  {
    id: "fallback-us-miami",
    title: "Civil Unrest in Miami",
    description: "Demonstrations and civil unrest reported in Miami-Dade County. Source coverage: miamiherald.com.",
    lat: 25.7617,
    lng: -80.1918,
    date: new Date().toISOString(),
    type: "civil_unrest",
    severity: "low",
    source: "miamiherald.com",
    sourceUrl: "https://www.miamiherald.com/",
    country: "United States",
    region: "Florida",
    zoomLevel: "local",
  },
];
