import { ConflictEvent } from "./types";

export const sampleConflicts: ConflictEvent[] = [
  {
    id: "1",
    title: "Eastern Ukraine Frontline Clashes",
    description:
      "Ongoing artillery exchanges and ground engagements along the eastern front. Multiple settlements affected with civilian infrastructure damage reported.",
    lat: 48.0159,
    lng: 37.8028,
    date: "2026-03-15",
    type: "armed_conflict",
    severity: "critical",
    casualties: 47,
    source: "ACLED",
    country: "Ukraine",
    region: "Eastern Europe",
  },
  {
    id: "2",
    title: "Sudan Civil War - Khartoum Fighting",
    description:
      "Heavy fighting between the Sudanese Armed Forces and the Rapid Support Forces in the capital region. Humanitarian corridor negotiations ongoing.",
    lat: 15.5007,
    lng: 32.5599,
    date: "2026-03-14",
    type: "armed_conflict",
    severity: "critical",
    casualties: 83,
    source: "ACLED",
    country: "Sudan",
    region: "East Africa",
  },
  {
    id: "3",
    title: "Myanmar Resistance Offensive",
    description:
      "Coordinated resistance forces launched operations against military junta positions in Sagaing Region. Multiple townships reported active clashes.",
    lat: 21.8787,
    lng: 95.9785,
    date: "2026-03-13",
    type: "armed_conflict",
    severity: "high",
    casualties: 29,
    source: "ACLED",
    country: "Myanmar",
    region: "Southeast Asia",
  },
  {
    id: "4",
    title: "Gaza Humanitarian Crisis Continues",
    description:
      "Continued military operations and severe humanitarian conditions. Aid delivery disruptions reported across multiple crossings.",
    lat: 31.3547,
    lng: 34.3088,
    date: "2026-03-15",
    type: "armed_conflict",
    severity: "critical",
    casualties: 156,
    source: "GDELT",
    country: "Palestine",
    region: "Middle East",
  },
  {
    id: "5",
    title: "Sahel Region - Mali Insurgent Attack",
    description:
      "Armed group attacked military outpost in northern Mali. Regional counterterrorism forces deployed in response.",
    lat: 16.7666,
    lng: -3.0026,
    date: "2026-03-12",
    type: "terrorism",
    severity: "high",
    casualties: 12,
    source: "ACLED",
    country: "Mali",
    region: "West Africa",
  },
  {
    id: "6",
    title: "DRC - M23 Advance Near Goma",
    description:
      "M23 rebel group made territorial gains near Goma, displacing thousands. UN peacekeeping mission monitoring the situation.",
    lat: -1.6585,
    lng: 29.2203,
    date: "2026-03-14",
    type: "armed_conflict",
    severity: "high",
    casualties: 34,
    source: "ACLED",
    country: "DR Congo",
    region: "Central Africa",
  },
  {
    id: "7",
    title: "Ethiopia - Amhara Region Tensions",
    description:
      "Clashes between federal forces and Fano militia in Amhara region. Communications blackout reported in several areas.",
    lat: 11.5936,
    lng: 37.3908,
    date: "2026-03-11",
    type: "political_violence",
    severity: "medium",
    casualties: 8,
    source: "ACLED",
    country: "Ethiopia",
    region: "East Africa",
  },
  {
    id: "8",
    title: "Colombia - ELN Peace Talks Stall",
    description:
      "ELN guerrilla activity increased following breakdown in peace negotiations. Security forces report skirmishes in Arauca department.",
    lat: 7.0847,
    lng: -70.7592,
    date: "2026-03-10",
    type: "armed_conflict",
    severity: "medium",
    casualties: 5,
    source: "GDELT",
    country: "Colombia",
    region: "South America",
  },
  {
    id: "9",
    title: "Somalia - Al-Shabaab Checkpoint Attack",
    description:
      "Al-Shabaab militants attacked a security checkpoint south of Mogadishu. Somali National Army and ATMIS forces responded.",
    lat: 2.0469,
    lng: 45.3182,
    date: "2026-03-13",
    type: "terrorism",
    severity: "high",
    casualties: 18,
    source: "ACLED",
    country: "Somalia",
    region: "East Africa",
  },
  {
    id: "10",
    title: "Haiti - Gang Violence in Port-au-Prince",
    description:
      "Armed gangs continued to expand territorial control in the capital. Multinational Security Support mission operations underway.",
    lat: 18.5944,
    lng: -72.3074,
    date: "2026-03-14",
    type: "political_violence",
    severity: "high",
    casualties: 22,
    source: "GDELT",
    country: "Haiti",
    region: "Caribbean",
  },
];
